apiVersion: v1
kind: Service
metadata:
  name: go-paint-app
  labels:
    app: go-paint-app
spec:
  type: ClusterIP
  selector:
    app: go-paint-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
