apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-paint-app
spec:
  ingressClassName: nginx
  rules:
  - host: "go-paint-app.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-paint-app
            port:
              number: 80
