apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: go-cluster
  region: ap-southeast-1
  version: "1.32"

managedNodeGroups:
- name: ng-al2
  instanceType: t3.small
  amiFamily: AmazonLinux2
  desiredCapacity: 1
  minSize: 1
  maxSize: 1
  volumeSize: 20
  labels:
    role: worker

iam:
  withOIDC: true
